default:
  image: ruby:2.7.2

stages:
  - setup
  - static_analysis
  - test

install_bundler:
  stage: setup
  script:
    - cd FeedBunch-app
    - gem install bundler --no-document

test-job1:
  stage: test
  script:
    - echo "This job tests something"

test-job2:
  stage: test
  script:
    - echo "This job tests something, but takes more time than test-job1."
    - echo "After the echo commands complete, it runs the sleep command for 20 seconds"
    - echo "which simulates a test that runs 20 seconds longer than test-job1"
    - sleep 20

deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."