default:
  image: ruby:2.7.2
  before_script:
    - bundle config set deployment 'true'
    - bundle config set path 'FeedBunch-app/vendor/bundle'
    - cd FeedBunch-app
    - bundle install --without development production

variables:
  RAILS_ENV: ci

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - 'FeedBunch-app/vendor/bundle'

stages:
  - install_dependencies
  - static_analysis
  - configure_tests
  - setup_database
  - test

install_gems:
  stage: install_dependencies
  script:
    - echo "Gems installed in cache"

bundle_audit:
  stage: static_analysis
  script:
    - bundle exec bundle-audit update
    - bundle exec bundle-audit check

brakeman:
  stage: static_analysis
  script:
    - bundle exec brakeman -z --no-pager

copy_configuration:
  stage: configure_tests
  script:
    - cp config/secrets_ci.yml config/secrets.yml
    - cp config/database.yml.ci config/database.yml

load_db:
  stage: setup_database
  script:
    - bundle exec rake db:schema:load

unit_tests:
  stage: test
  variables:
    TEST_SUITE: unit
  script:
    - bundle exec rake spec:ci

acceptance_tests_1:
  stage: test
  variables:
    TEST_SUITE: acceptance_1
  script:
    - bundle exec rake spec:ci

acceptance_tests_2:
  stage: test
  variables:
    TEST_SUITE: acceptance_2
  script:
    - bundle exec rake spec:ci