default:
  image: ruby:2.7.2
  before_script:
    - apt-get update -qy
    - apt-get -o dir::cache::archives="apt-cache" install -y nodejs firefox
    - cd FeedBunch-app
    - bundle config set deployment 'true'
    - bundle config set path 'vendor'
    - bundle config set without 'development production'
    - bundle install

variables:
  RAILS_ENV: ci

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - 'FeedBunch-app/vendor'
    - 'apt-cache'

stages:
  - install_dependencies
  - static_analysis
  - configure_rails
  - setup_database
  - test

install_deps:
  stage: install_dependencies
  script:
    - echo "Installed dependencies"

bundle_audit:
  stage: static_analysis
  script:
    - bundle exec bundle-audit update
    - bundle exec bundle-audit check

brakeman:
  stage: static_analysis
  script:
    - bundle exec brakeman -z --no-pager

copy_configuration:
  stage: configure_rails
  before_script:
    - cd FeedBunch-app
  script:
    - cp config/secrets_ci.yml config/secrets.yml
    - cp config/database.yml.ci config/database.yml

load_db:
  stage: setup_database
  script:
    - cp config/secrets_ci.yml config/secrets.yml
    - cp config/database.yml.ci config/database.yml
    - bundle exec rake db:schema:load

unit_tests:
  stage: test
  variables:
    TEST_SUITE: unit
  script:
    - cp config/secrets_ci.yml config/secrets.yml
    - cp config/database.yml.ci config/database.yml
    - bundle exec rake spec:ci

acceptance_tests_1:
  stage: test
  variables:
    TEST_SUITE: acceptance_1
  script:
    - cp config/secrets_ci.yml config/secrets.yml
    - cp config/database.yml.ci config/database.yml
    - bundle exec rake spec:ci

acceptance_tests_2:
  stage: test
  variables:
    TEST_SUITE: acceptance_2
  script:
    - cp config/secrets_ci.yml config/secrets.yml
    - cp config/database.yml.ci config/database.yml
    - bundle exec rake spec:ci