default:
  image: ruby:2.7.2
  before_script:
    # Install nodejs and firefox
    - apt-get update -qy
    - apt-get -o dir::cache::archives="apt-cache" install -y nodejs iceweasel

    # Install geckodriver
    - mkdir -p geckodriver-cache
    - cd geckodriver-cache
    - GECKODRIVER_VERSION=$(curl https://github.com/mozilla/geckodriver/releases/latest | grep -Po 'v[0-9]+.[0-9]+.[0-9]+')
    - wget --no-clobber https://github.com/mozilla/geckodriver/releases/download/$GECKODRIVER_VERSION/geckodriver-$GECKODRIVER_VERSION-linux64.tar.gz
    - tar -zxf geckodriver-$GECKODRIVER_VERSION-linux64.tar.gz -C /usr/local/bin
    - chmod +x /usr/local/bin/geckodriver

    # Install gems in bundle
    - cd ../FeedBunch-app
    - bundle config set deployment 'true'
    - bundle config set path 'vendor/gems'
    - bundle config set without 'development production'
    - bundle install

variables:
  RAILS_ENV: ci

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - 'FeedBunch-app/vendor/gems'
    - 'apt-cache'
    - 'geckodriver-cache'

stages:
  - install_dependencies
  - static_analysis
  - setup_database
  - test

install_deps:
  stage: install_dependencies
  script:
    - echo "Installed dependencies"

bundle_audit:
  stage: static_analysis
  script:
    - bundle exec bundle-audit update
    - bundle exec bundle-audit check

brakeman:
  stage: static_analysis
  script:
    - bundle exec brakeman -z --no-pager

load_db:
  stage: setup_database
  script:
    - cp config/secrets_ci.yml config/secrets.yml
    - cp config/database.yml.ci config/database.yml
    - bundle exec rake db:schema:load

unit_tests:
  stage: test
  variables:
    TEST_SUITE: unit
  script:
    - cp config/secrets_ci.yml config/secrets.yml
    - cp config/database.yml.ci config/database.yml
    - bundle exec rake spec:ci

acceptance_tests_1:
  stage: test
  variables:
    TEST_SUITE: acceptance_1
  script:
    - cp config/secrets_ci.yml config/secrets.yml
    - cp config/database.yml.ci config/database.yml
    - bundle exec rake spec:ci

acceptance_tests_2:
  stage: test
  variables:
    TEST_SUITE: acceptance_2
  script:
    - cp config/secrets_ci.yml config/secrets.yml
    - cp config/database.yml.ci config/database.yml
    - bundle exec rake spec:ci

acceptance_tests_3:
  stage: test
  variables:
    TEST_SUITE: acceptance_3
  script:
    - cp config/secrets_ci.yml config/secrets.yml
    - cp config/database.yml.ci config/database.yml
    - bundle exec rake spec:ci

acceptance_tests_4:
  stage: test
  variables:
    TEST_SUITE: acceptance_4
  script:
    - cp config/secrets_ci.yml config/secrets.yml
    - cp config/database.yml.ci config/database.yml
    - bundle exec rake spec:ci