##
# Main controller of the application. Options set here affect the whole application.

class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :set_locale

  private

  ##
  # Set locale for the current request.
  # If a "locale" parameter is passed, this will be the value used. Otherwise the default locale :en will be used.
  #
  # If the locale passed does not exist, the default locale :en will be used if the following is set in application.rb:
  #   config.i18n.fallbacks = true

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  ##
  # Set default options for all URLs generated by url_for method. This includes URLs generated by helpers like
  # root_path, feeds_url, feeds_path, etc.
  #
  # Currently this method adds the "locale" URL parameter to all such URLs, setting it to the current locale. This means
  # that if e.g. current locale is :es (spanish), the feeds_path helper would print this:
  #   /feeds?locale=es
  #
  # For more information see the
  # {Rails internationalization guide}[http://guides.rubyonrails.org/i18n.html#setting-the-locale-from-the-url-params].

  def default_url_options(options={})
    logger.debug "default_url_options is passed options: #{options.inspect}"
    return { locale: I18n.locale }
  end

end
